name: 1-buildingblock
on: 
   pull_request: 

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run: echo "Hello World!!"
    echo-exit:
        runs-on: ubuntu-latest
        steps: 
            - name: Successful step to say bye
              run: |
                echo "Fail"
                exit 0
            - name: Say Bye
              run: echo "Goodbye!!" 