name: 1-buildingblock
on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run: echo "Hello World!!"
    echo-exit:
        runs-on: ubuntu-latest
        steps: 
            - name: failed step
              run: |
                echo "Fail"
                exit 1
            - name: Say Bye
              run: echo "Goodbye!!" 