name: 2 Workflow events demo

on: 
     pull_request: 
     # schedule:  
      #  - cron: '*/5 * * * *'
     workflow_dispatch: # Allows manual triggering
    
permissions:
  actions: read
  contents: read

jobs: 
    echo: 
        runs-on: ubuntu-latest 
        steps:
           - name: Show the trigger
             run: echo "This is triggered by a(n) ${{ github.event_name }}"
